# .graphclientrc.yml
sources:
  - name: weather-auction
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/61274/orally-weather-auction/0.2.1

documents:
  - ./weather-auction-query.graphql