[package]
name = "oracle_factory"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = "0.8.0"
ic-cdk = "0.6.8"
ic-cdk-macros = "0.6.8"
serde_json = "1.0.81"
serde = "1.0.126"
serde_bytes = "0.11.7"
canistergeek_ic_rust = "0.3.1"

